export const SPINNER_BASE_SIZE = 100;
export const SPINNER_BASE_STROKE_WIDTH = 10;
export const SPINNER_SIZE_HOST_REDUCE_RATIO = 0.8;
export const SPINNER_BASE_SIZE_REDUCED = SPINNER_BASE_SIZE * SPINNER_SIZE_HOST_REDUCE_RATIO;
